import { StyleSheet } from 'react-native';
import { COLORS, RADIUS, SHADOW, SPACE, TYPE } from '../utils/app-utils';

const BOTTOM_NAV_HEIGHT = 86;

export const appStyles = StyleSheet.create({
  container: { flex: 1 },
  rootLayout: { flex: 1, position: 'relative' },
  appFrame: { flex: 1, overflow: 'hidden', paddingBottom: BOTTOM_NAV_HEIGHT },
  scrollContent: { padding: SPACE.xl, gap: SPACE.lg },

  hero: { paddingTop: SPACE.sm, paddingBottom: SPACE.xs, gap: SPACE.sm },
  heroTitle: { ...TYPE.xl },
  heroSub: { ...TYPE.body },

  authBrandWordmark: { ...TYPE.lg, marginLeft: 4, letterSpacing: 0.4 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACE.md,
    paddingBottom: SPACE.xs,
    width: '100%',
    minHeight: 48,
    alignSelf: 'stretch',
  },
  logoMark: { width: 40, height: 40, borderRadius: RADIUS.md, alignItems: 'center', justifyContent: 'center' },
  logoText: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', lineHeight: 20 },
  brandName: { ...TYPE.lg, letterSpacing: 3, marginLeft: 4 },
  logoContainer: { backgroundColor: COLORS.light.primary, padding: SPACE.md, borderRadius: RADIUS.md },
  logoImage: { width: 80, height: 80, resizeMode: 'contain' },
  headerTitle: { ...TYPE.lg },
  headerSub: { ...TYPE.meta, marginTop: 1 },

  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingLeft: 14,
    paddingRight: 4,
    height: 52,
    gap: 10,
    ...SHADOW.card,
  },
  searchInput: { flex: 1, fontSize: TYPE.body.fontSize, fontWeight: TYPE.body.fontWeight },
  searchDivider: { width: 1, height: 24, opacity: 0.5 },
  searchFilterArea: {
    paddingHorizontal: 12,
    paddingVertical: 14,
    minHeight: 44,
    justifyContent: 'center',
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACE.xs,
  },

  autocompleteBox: {
    borderWidth: 1,
    borderTopWidth: 0,
    borderBottomLeftRadius: RADIUS.md,
    borderBottomRightRadius: RADIUS.md,
    marginTop: -4,
    paddingTop: 4,
    overflow: 'hidden',
  },
  acItem: { flexDirection: 'row', alignItems: 'center', gap: SPACE.sm, paddingHorizontal: 14, paddingVertical: 12, minHeight: 44 },
  acSearchIcon: { ...TYPE.meta },
  acItemText: { ...TYPE.body },

  chipsRow: { gap: SPACE.sm, paddingVertical: 2 },
  chip: {
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 14,
    paddingVertical: 9,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipText: { ...TYPE.meta },

  filterRow: { flexDirection: 'row', gap: SPACE.sm, alignItems: 'center' },
  cityInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
    ...TYPE.body,
  },
  filterBtn: {
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBtnText: { ...TYPE.meta },
  goBtn: { width: 44, height: 44, borderRadius: RADIUS.md, alignItems: 'center', justifyContent: 'center' },
  goBtnText: { ...TYPE.heading, color: '#FFFFFF' },

  filterPanel: { borderWidth: 1, borderRadius: RADIUS.md, padding: SPACE.lg, gap: SPACE.md },
  filterCompactPanel: { padding: SPACE.md, gap: SPACE.md },
  filterPanelHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACE.sm },
  filterCompactHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACE.sm },
  filterCompactTitle: { ...TYPE.heading },
  filterSectionBlock: { gap: SPACE.sm },
  filterSectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACE.sm },
  filterSectionTitle: { ...TYPE.label, marginBottom: 10 },
  filterCompactSection: { gap: SPACE.sm },
  filterCompactSectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACE.sm },
  filterCompactSectionTitle: { ...TYPE.label },
  filterResetBtn: {
    minHeight: 30,
    borderRadius: RADIUS.full,
    paddingHorizontal: SPACE.sm,
    paddingVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterResetBtnText: { ...TYPE.meta },
  filterChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACE.sm },
  kassenartCompactToggle: {
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    padding: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  kassenartCompactToggleBtn: {
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: 36,
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  kassenartCompactToggleText: { ...TYPE.meta },
  filterCompactChip: {
    minHeight: 36,
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
  },
  filterCompactChipText: { ...TYPE.meta },
  filterSearchField: {
    minHeight: 40,
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterSearchInput: { flex: 1, ...TYPE.meta, paddingVertical: 0 },
  filterSearchResults: {
    borderWidth: 1,
    borderRadius: RADIUS.md,
    overflow: 'hidden',
  },
  filterSearchResultItem: {
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACE.sm,
  },
  filterSearchResultText: { ...TYPE.meta, flex: 1 },
  filterSelectedChip: {
    maxWidth: '100%',
    minHeight: 34,
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterSelectedChipText: { ...TYPE.meta, maxWidth: 220 },
  filterEmptyText: { ...TYPE.meta },
  sectionBadgeRow: { flexDirection: 'row', alignItems: 'center', gap: SPACE.sm, flexWrap: 'wrap', marginBottom: 6 },
  inlineMetaPill: { borderRadius: RADIUS.full, paddingHorizontal: 10, paddingVertical: 5 },
  inlineMetaPillText: { ...TYPE.label, fontSize: 11, lineHeight: 11 },
  metaNote: { ...TYPE.meta },
  optionalInlineLabel: { fontWeight: '400', textTransform: 'none', letterSpacing: 0, fontSize: 11, lineHeight: 14 },
  collapseToggle: {
    minHeight: 44,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACE.md,
    paddingVertical: SPACE.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACE.sm,
  },
  kassenartRow: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACE.sm },
  kassenartBtn: {
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 44,
    alignItems: 'center',
  },
  kassenartText: { ...TYPE.meta },
  kassenartToggleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACE.sm },
  kassenartToggleCard: {
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 52,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACE.md,
    paddingVertical: SPACE.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACE.sm,
  },
  kassenartToggleText: { ...TYPE.meta, flex: 1 },
  kassenartToggleCheck: {
    width: 22,
    height: 22,
    borderRadius: RADIUS.full,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterTile: {
    minHeight: 56,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACE.md,
    paddingVertical: SPACE.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACE.md,
  },
  filterTileIcon: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterTileTitle: { ...TYPE.heading },
  filterTileMeta: { ...TYPE.meta },
  filterTileCheck: {
    width: 22,
    height: 22,
    borderRadius: RADIUS.full,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedFiltersRow: { gap: SPACE.sm, paddingVertical: 2, paddingRight: SPACE.sm },
  selectedFilterChip: {
    maxWidth: 220,
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  selectedFilterChipText: { ...TYPE.meta, flexShrink: 1 },
  multiSelectList: { gap: SPACE.sm },
  multiSelectOption: {
    minHeight: 52,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACE.md,
    paddingVertical: SPACE.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACE.md,
  },
  multiSelectOptionText: { ...TYPE.body, flex: 1 },
  multiSelectCheck: {
    width: 22,
    height: 22,
    borderRadius: RADIUS.full,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterMoreBtn: {
    minHeight: 40,
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: SPACE.md,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
  },
  filterMoreBtnText: { ...TYPE.meta },
  checkRow: { flexDirection: 'row', alignItems: 'center', gap: SPACE.sm, paddingVertical: 8, minHeight: 44 },
  checkbox: { width: 22, height: 22, borderRadius: RADIUS.sm, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  checkmark: { color: '#FFFFFF', ...TYPE.label, fontSize: 12, lineHeight: 12, letterSpacing: 0, textTransform: 'none' },
  checkLabel: { ...TYPE.body, flex: 1 },
  switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  switchTitle: { ...TYPE.body, fontWeight: '600', marginBottom: 2 },
  switchLabel: { ...TYPE.meta },

  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: SPACE.sm },
  sectionLabel: { ...TYPE.heading },
  approvedPill: { borderRadius: RADIUS.full, paddingHorizontal: 10, paddingVertical: 4 },
  approvedPillText: { ...TYPE.meta },
  metaPill: { borderRadius: RADIUS.full, paddingHorizontal: 10, paddingVertical: 5 },
  metaPillText: { ...TYPE.meta },

  resultCard: { borderWidth: 1, borderRadius: RADIUS.lg, padding: 18, gap: 14, ...SHADOW.card },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: SPACE.md },
  avatar: { width: 56, height: 56, borderRadius: RADIUS.full },
  cardName: { ...TYPE.heading, marginBottom: 2 },
  cardTitle: { ...TYPE.meta },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tag: { borderRadius: RADIUS.full, paddingHorizontal: 10, paddingVertical: 5 },
  tagText: { ...TYPE.meta },
  practiceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: SPACE.md,
    minHeight: 56,
  },
  practiceInitial: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  practiceInitialText: { ...TYPE.heading, fontWeight: '700' },
  practiceName: { ...TYPE.body, fontWeight: '600' },
  practiceCity: { ...TYPE.meta, marginTop: 1 },
  practiceArrow: { fontSize: 18 },
  filterIconBtn: {
    width: 48,
    height: 48,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterIconText: { fontSize: 20 },
  filterBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadgeText: { ...TYPE.label, color: '#FFFFFF', fontSize: 11, lineHeight: 11, letterSpacing: 0, textTransform: 'none' },
  distBadge: { borderRadius: RADIUS.full, paddingHorizontal: 8, paddingVertical: 3, marginRight: 6 },
  distBadgeText: { ...TYPE.meta, fontWeight: '700' },

  backBtn: { paddingVertical: 10, minHeight: 44, justifyContent: 'center', alignSelf: 'flex-start' },
  backBtnText: { ...TYPE.body, fontWeight: '600' },
  practiceHeader: { borderWidth: 1, borderRadius: RADIUS.lg, padding: 20, alignItems: 'center', gap: 6, ...SHADOW.card },
  practiceLogoLarge: {
    width: 64,
    height: 64,
    borderRadius: RADIUS.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  practiceLogoText: { color: '#FFFFFF', fontSize: 26, fontWeight: '800', lineHeight: 26 },
  practiceLogoCross: { position: 'absolute', top: 8, right: 8, width: 18, height: 18 },
  plusBarH: { position: 'absolute', top: '38%', left: 0, right: 0, height: 5, borderRadius: 3 },
  plusBarV: { position: 'absolute', left: '38%', top: 0, bottom: 0, width: 5, borderRadius: 3 },
  practiceHeaderName: { ...TYPE.lg },
  practiceHeaderCity: { ...TYPE.body },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  detailIcon: { fontSize: 18 },
  detailText: { ...TYPE.body, flex: 1 },
  miniCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACE.md,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: 14,
  },
  miniAvatar: { width: 44, height: 44, borderRadius: RADIUS.full },

  ctaBtn: { borderRadius: RADIUS.md, paddingVertical: 12, minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  ctaBtnText: { ...TYPE.heading, color: '#FFFFFF' },
  ctaBtnSecondary: { borderRadius: RADIUS.md, paddingVertical: 12, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  ctaBtnSecondaryText: { ...TYPE.heading },

  emptyState: { borderWidth: 1, borderRadius: RADIUS.lg, padding: SPACE.xxl, alignItems: 'center', gap: SPACE.sm },
  emptyIcon: { fontSize: 32 },
  emptyTitle: { ...TYPE.heading },
  emptyBody: { ...TYPE.body, textAlign: 'center' },
  emptyActions: { flexDirection: 'row', gap: 10, marginTop: 8, width: '100%' },
  emptyActionBtn: { flex: 1, borderRadius: RADIUS.md, paddingVertical: 12, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  emptyActionText: { ...TYPE.meta, fontWeight: '700' },
  emptyInlineState: { borderWidth: 1, borderRadius: RADIUS.md, padding: 14, marginHorizontal: 16, marginTop: 8 },

  noticeBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: 14,
    width: '100%',
  },
  lockBadge: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  noticeIcon: { fontSize: 20, marginTop: 1, width: 24, textAlign: 'center' },
  noticeTitle: { ...TYPE.body, fontWeight: '700', marginBottom: 3 },
  noticeBody: { ...TYPE.meta, flex: 1, flexShrink: 1 },
  infoCard: { borderWidth: 1, borderRadius: RADIUS.lg, padding: 20, gap: 10, ...SHADOW.card },
  infoTitle: { ...TYPE.lg },
  infoBody: { ...TYPE.body },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    borderBottomWidth: 1,
    paddingBottom: 14,
  },
  stepNum: { width: 32, height: 32, borderRadius: RADIUS.sm, alignItems: 'center', justifyContent: 'center' },
  stepNumText: { color: '#FFFFFF', ...TYPE.body, fontWeight: '700', lineHeight: 18 },
  stepTitle: { ...TYPE.body, fontWeight: '600', marginBottom: 2 },
  stepBody: { ...TYPE.meta },
  registerBtn: { borderRadius: RADIUS.md, paddingVertical: 14, minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 4 },
  registerBtnText: { ...TYPE.heading, color: '#FFFFFF' },
  loginLink: { textAlign: 'center', ...TYPE.body, fontWeight: '600', paddingVertical: 12 },

  optionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    minHeight: 56,
  },
  optionLabel: { ...TYPE.body, fontWeight: '500' },
  optionValue: { ...TYPE.meta },

  therapistAvatarLarge: { width: 80, height: 80, borderRadius: RADIUS.full, marginBottom: 4 },
  therapistAvatarSmall: { width: 40, height: 40 },
  practiceHeaderInitial: { width: 64, height: 64, borderRadius: RADIUS.md, alignItems: 'center', justifyContent: 'center' },
  practiceHeaderInitialText: { color: '#FFFFFF', fontSize: 24, fontWeight: '800', lineHeight: 24 },
  infoSection: { borderWidth: 1, borderRadius: RADIUS.md, padding: 18, gap: 10, ...SHADOW.card },
  profileName: { ...TYPE.lg },
  therapistName: { ...TYPE.heading },
  therapistTitle: { ...TYPE.meta },
  profileNameRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap', justifyContent: 'center' },
  verifiedBadge: { borderRadius: RADIUS.full, paddingHorizontal: 8, paddingVertical: 3 },
  verifiedText: { ...TYPE.meta, fontWeight: '700' },
  detailInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  detailInfoLabel: { ...TYPE.label },
  detailInfoValue: { ...TYPE.body, marginTop: 1 },
  input: {
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 48,
    ...TYPE.body,
    outlineWidth: 0,
  },
  inputField: {
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 48,
    ...TYPE.body,
    outlineWidth: 0,
  },

  themeToggleRow: { flexDirection: 'row', gap: 6 },
  themeBtn: {
    borderWidth: 1,
    borderRadius: RADIUS.full,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  themeBtnText: { ...TYPE.meta, fontWeight: '600' },

  regProgressRow: { flexDirection: 'row', gap: 4, marginBottom: 4 },
  regProgressBar: { height: 4, borderRadius: 2, flex: 1 },
  regStepTitle: { fontSize: 15, fontWeight: '700', marginBottom: 4 },
  regStepSub: { ...TYPE.body, marginBottom: 4 },
  regInput: {
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 44,
    fontSize: TYPE.body.fontSize,
    fontWeight: TYPE.body.fontWeight,
    outlineWidth: 0,
  },
  regTextarea: { minHeight: 100, textAlignVertical: 'top', paddingTop: 12 },

  previewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderBottomWidth: 1,
    gap: 12,
  },
  previewLabel: { ...TYPE.meta, fontWeight: '600', flex: 1 },
  previewValue: { ...TYPE.meta, flex: 2, textAlign: 'right' },
});
